### ISSUE TITLE
what is the dimension of the bed?

### ISSUE THREAD

**Issue by amrithmmh** [makertum/Makertum-MK1#1]
what is the dimension of the heaterbed and can it be scaled to 1000mmx1000mm for big 3d printer build?

**Comment by amrithmmh** [comment]
please reply

**Comment by fajardocj** [comment]
+1, pls respond

**Comment by benhadad** [comment]
The bed cannot be directly scaled as this will change the resistance of the traces. A new layout would be required.

**Comment by amrithmmh** [comment]
thank you. appreciate it!
